[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.60.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "https://ianeveperry.com/*"
  to = "https://eveperry.com/:splat"
  status = 301
  force = true
